name: Build

on: push

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node
      uses: actions/setup-node@v1
      with: {node-version: 12.x}
    
    - run: npm install
    - run: npm run build

  build_ui:
    name: Build UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - run: npm install
    - run: npm run build 
