name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build API
      run: |
        cd api
        npm install
        npm run build
    
    - name: Test API
      run: |
        cd api
        echo $(pwd)
        npm run test
    
    - name: Build UI
      run: |
        cd ui
        npm install
        npm run build
        
    - name: Test UI
      run: |
        cd ui
        npm run test
    
