name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}} ${{github.sha}}
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with: 
        working-directory: |
          api
          ui
  
    - name: Build API
      run: npm run build
      working-directory: api
    
    - name: Build UI
      run: npm run build
      working-directory: ui
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deployment
    #if: github.ref == 'refs/heads/master'
    needs: build
    steps:
    - run: echo ${{github.ref}} ${{github.sha}}
    - uses: octokit/request-action@v2.x
      with:
        route: POST /repos/${{github.repository}}/deployment
        ref: ${{github.ref}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    
    
    
