name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: |
          api
          ui
  
    - name: Build API
      run: npm run build
      working-directory: api
    
    - name: Build UI
      run: npm run build
      working-directory: ui
